### ISSUE TITLE
你好，docker-compose up部署完成后，访问系统前端报错

### ISSUE THREAD

**Issue by cfy3133** [tongdun/data4test#2]
![image](https://github.com/user-attachments/assets/4dce13d5-2f20-42f6-9c82-6ade532e5030)
查看日志显示正常：
![image](https://github.com/user-attachments/assets/5b90b90b-7fdc-4e1d-97ab-82de3a8662ca)
![image](https://github.com/user-attachments/assets/9eb7782f-33ca-480f-b809-4f37e331f3d5)

**Comment by camrionnvmff** [comment]
环境冲突问题，建议用servbay调试 试试

**Comment by cfy3133** [comment]
感谢作者回复，找到原因了，因为某个广告拦截插件工具导致的：
![image](https://github.com/user-attachments/assets/3aa15ac7-6eef-4d7c-84ae-6fe20ad0ec40)
